/**
 * @file ws-auth.ts
 * @description Socket.IO server-level authentication middleware.
 *
 * Registered via io.use() in apps/api/src/websocket/index.ts. This middleware
 * runs ONCE per new WebSocket connection handshake. It:
 *   1. Extracts the JWT from socket.handshake.auth.token
 *   2. Verifies the JWT signature and expiration using jsonwebtoken
 *   3. Validates the token type is 'access' (rejects refresh tokens)
 *   4. Checks the token's JTI against the Redis blacklist for revoked sessions (R33)
 *   5. On success, sets socket.data.userId, socket.data.email, socket.data.jti,
 *      and socket.data.correlationId (R29)
 *   6. On failure, rejects the connection with next(new Error(...))
 *
 * Architecture Rules Enforced:
 * - R9:  Authentication on all protected routes — ALL WebSocket connections require valid JWT
 * - R33: Session revocation — checks Redis blacklist keyed by JTI on every connection
 * - R23: Log hygiene — NEVER logs JWT tokens, passwords, or sensitive data
 * - R28: Structured logging only — zero console.log/warn/error calls
 * - R29: Correlation ID propagation — assigns UUID v4 per connection
 * - R7:  Zero warnings build — strict TypeScript, explicit types, no any
 * - R17: Interface-driven dependencies — uses ICacheProvider, not concrete Redis client
 */

import type { Socket } from 'socket.io';
import type { ICacheProvider } from '../../domain/interfaces/ICacheProvider';
import jwt from 'jsonwebtoken';
import { v4 as uuidv4 } from 'uuid';

// ---------------------------------------------------------------------------
// Exported Interfaces
// ---------------------------------------------------------------------------

/**
 * Expected JWT payload structure matching tokens generated by AuthService.
 *
 * This interface is aligned with the access tokens issued by
 * AuthService.generateAccessToken(). The 'type' field distinguishes
 * access tokens from refresh tokens — only 'access' tokens are accepted
 * for WebSocket connections.
 */
export interface JwtPayload {
  /** User identifier (maps to User.id in the database) */
  sub: string;

  /** User email address */
  email: string;

  /** JWT ID — unique per token, used as Redis blacklist key for revocation (R33) */
  jti: string;

  /** Token type discriminator: 'access' for access tokens, 'refresh' for refresh tokens */
  type: string;

  /** Issued-at timestamp (Unix seconds) */
  iat: number;

  /** Expiration timestamp (Unix seconds) */
  exp: number;
}

/**
 * Shape of socket.data populated by the authentication middleware.
 *
 * After successful authentication, downstream WebSocket event handlers
 * can safely access these fields from socket.data to identify the
 * authenticated user and trace operations via the correlation ID.
 *
 * Usage in handlers:
 * ```typescript
 * const userId = socket.data.userId as string;
 * const correlationId = socket.data.correlationId as string;
 * ```
 */
export interface AuthenticatedSocketData {
  /** Authenticated user's unique identifier (from JWT sub claim) */
  userId: string;

  /** Authenticated user's email address (from JWT email claim) */
  email: string;

  /** JWT ID for potential mid-connection revocation checks */
  jti: string;

  /** UUID v4 correlation ID unique to this WebSocket connection (R29) */
  correlationId: string;
}

// ---------------------------------------------------------------------------
// Factory Function
// ---------------------------------------------------------------------------

/**
 * Creates a Socket.IO server-level authentication middleware.
 *
 * This factory function returns a middleware compatible with Socket.IO's
 * `io.use()` registration pattern. The middleware verifies JWT tokens
 * from the WebSocket handshake, checks the Redis token blacklist for
 * session revocation (R33), and populates socket.data with authenticated
 * user information and a correlation ID (R29).
 *
 * @param jwtSecret - The JWT secret key used to verify token signatures.
 *   Passed directly from env.JWT_SECRET in the composition root.
 * @param cacheProvider - The cache provider interface (backed by Redis)
 *   used to check the token blacklist for session revocation.
 * @returns A Socket.IO middleware function suitable for io.use() registration.
 *
 * @example
 * ```typescript
 * import { createWsAuthMiddleware } from './middleware/ws-auth';
 *
 * const io = new Server(httpServer);
 * io.use(createWsAuthMiddleware(env.JWT_SECRET, cacheProvider));
 *
 * io.on('connection', (socket) => {
 *   // socket.data.userId is guaranteed to be set
 *   // socket.data.correlationId is guaranteed to be set
 *   const userId = socket.data.userId as string;
 * });
 * ```
 */
export function createWsAuthMiddleware(
  jwtSecret: string,
  cacheProvider: ICacheProvider
): (socket: Socket, next: (err?: Error) => void) => void {
  /**
   * Inner middleware executed on every new WebSocket connection attempt.
   *
   * The middleware is async because the Redis blacklist check (R33)
   * requires an await. Socket.IO supports async middleware — the next()
   * callback is called after all async operations complete.
   */
  return (socket: Socket, next: (err?: Error) => void): void => {
    (async (): Promise<void> => {
      // ------------------------------------------------------------------
      // Step 1: Extract token from handshake auth object
      // ------------------------------------------------------------------
      // Socket.IO clients send auth data during the connection handshake:
      //   const socket = io('http://...', { auth: { token: 'eyJhbG...' } });
      // The token is accessible at socket.handshake.auth.token
      const token: string | undefined =
        (socket.handshake.auth as Record<string, unknown> | undefined)?.token as
          | string
          | undefined;

      if (!token || typeof token !== 'string') {
        next(new Error('Authentication error: No token provided'));
        return;
      }

      // ------------------------------------------------------------------
      // Step 2: Verify JWT signature and decode payload
      // ------------------------------------------------------------------
      // jwt.verify() validates the signature against jwtSecret, checks
      // the 'exp' claim for expiration, and decodes the payload.
      // If verification fails (expired, invalid signature, malformed),
      // the error is caught and the connection is rejected.
      //
      // CRITICAL (R23): The token string value MUST NOT appear in error
      // messages or log output. Only safe metadata (userId, jti) is used.
      let decoded: JwtPayload;
      try {
        decoded = jwt.verify(token, jwtSecret) as JwtPayload;
      } catch (_verifyError: unknown) {
        next(new Error('Authentication error: Invalid token'));
        return;
      }

      // ------------------------------------------------------------------
      // Step 3: Validate required payload fields
      // ------------------------------------------------------------------
      // Ensure the decoded payload contains all required fields for a
      // valid access token. This guards against tokens with missing
      // or malformed claims.
      if (
        !decoded.sub ||
        !decoded.email ||
        !decoded.jti ||
        !decoded.type
      ) {
        next(new Error('Authentication error: Malformed token payload'));
        return;
      }

      // ------------------------------------------------------------------
      // Step 4: Validate token type — only accept access tokens
      // ------------------------------------------------------------------
      // Refresh tokens must NOT be used for WebSocket connections.
      // Only access tokens (type === 'access') are accepted.
      if (decoded.type !== 'access') {
        next(new Error('Authentication error: Invalid token type'));
        return;
      }

      // ------------------------------------------------------------------
      // Step 5: Check Redis blacklist for session revocation (R33)
      // ------------------------------------------------------------------
      // When a user's session is revoked (via revoke or revoke-all),
      // the AuthService stores the JWT's JTI in Redis with key format
      // 'blacklist:${jti}' and a TTL equal to the token's remaining
      // expiry time. If this key exists, the token has been revoked
      // and the connection must be rejected.
      const isBlacklisted: boolean = await cacheProvider.exists(
        `blacklist:${decoded.jti}`
      );

      if (isBlacklisted) {
        next(new Error('Authentication error: Token has been revoked'));
        return;
      }

      // ------------------------------------------------------------------
      // Step 6: Set authenticated data on socket.data
      // ------------------------------------------------------------------
      // Downstream event handlers access these fields to identify the
      // authenticated user and trace operations:
      //   socket.data.userId        — user identifier for all operations
      //   socket.data.email         — email for logging context
      //   socket.data.jti           — JTI for mid-connection revocation checks
      //   socket.data.correlationId — unique ID for tracing (R29)
      socket.data.userId = decoded.sub;
      socket.data.email = decoded.email;
      socket.data.jti = decoded.jti;
      socket.data.correlationId = uuidv4();

      // ------------------------------------------------------------------
      // Step 7: Allow the connection
      // ------------------------------------------------------------------
      next();
    })().catch((_unexpectedError: unknown) => {
      // Catch any unexpected errors (e.g., Redis connection failure during
      // blacklist check) and reject the connection with a generic message.
      // CRITICAL (R23): Do NOT include error details that might leak
      // sensitive information. Only a generic server error message is used.
      next(new Error('Authentication error: Internal server error'));
    });
  };
}
